#!/usr/bin/env sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '^client/.*\.\(js\|ts\|tsx\|css\|json\)$')

# Check if there are any files to format
if [ -n "$STAGED_FILES" ]; then
  echo "Formatting staged files in client directory with Prettier..."
  
  # Run Prettier on each staged file
  echo "$STAGED_FILES" | xargs npx prettier --write

  # Add the formatted files back to the staging area
  echo "$STAGED_FILES" | xargs git add
else
  echo "No matching staged files in client directory to format."
fi